export const BLOCKER_VERSION = '1.0.0-beta.4';

export const STORAGE_KEYS = Object.freeze({
  datasetMeta: 'bfb:dataset-meta',
  settings: 'bfb:settings',
  auth: 'bfb:auth',
  session: 'bfb:session',
  localDataset: 'bfb:local-dataset',
  localSettings: 'bfb:local-settings',
  managerSessions: 'bfb:manager-sessions',
  managerTabs: 'bfb:manager-tabs',
  adminSessions: 'bfb:admin-sessions'
});

export const DEFAULT_SETTINGS = Object.freeze({
  enabled: true,
  blockTerms: true,
  blockLinks: true,
  lockManager: true,
  unlockTtlMinutes: 5,
  redirectTerms: false,
  redirectTermsUrl: '',
  redirectLinks: false,
  redirectLinksUrl: ''
});

export const MESSAGE = Object.freeze({
  getBootstrap: 'BFB_GET_BOOTSTRAP',
  getState: 'BFB_GET_STATE',
  checkAccess: 'BFB_CHECK_ACCESS',
  popupUnlockOpen: 'BFB_POPUP_UNLOCK_OPEN',
  quickAddItem: 'BFB_QUICK_ADD_ITEM',
  unlock: 'BFB_UNLOCK',
  lock: 'BFB_LOCK',
  adminUnlock: 'BFB_ADMIN_UNLOCK',
  adminLock: 'BFB_ADMIN_LOCK',
  updateAdminSettings: 'BFB_UPDATE_ADMIN_SETTINGS',
  addItem: 'BFB_ADD_ITEM',
  removeItem: 'BFB_REMOVE_ITEM',
  importList: 'BFB_IMPORT_LIST',
  replaceAll: 'BFB_REPLACE_ALL',
  syncNow: 'BFB_SYNC_NOW',
  getGitHubSyncStatus: 'BFB_GET_GITHUB_SYNC_STATUS',
  saveGitHubSyncConfig: 'BFB_SAVE_GITHUB_SYNC_CONFIG',
  downloadGitHubLists: 'BFB_DOWNLOAD_GITHUB_LISTS',
  uploadGitHubLists: 'BFB_UPLOAD_GITHUB_LISTS',
  openManager: 'BFB_OPEN_MANAGER'
});

export const DATASET_PREFIX = 'bfb:data:';
export const MAX_CHUNK_BYTES = 6500;
export const ADMIN_SESSION_TTL_MS = 5 * 60 * 1000;

export const COMPLETE_EXCLUSION_HOSTS = Object.freeze([
  'archive.org',
  'iltalehti.fi',
  'is.fi',
  'youtube.com',
  'wikipedia.org',
  'netflix.com',
  'runescape.wiki',
  'runescape.com',
  'chatgpt.com',
  'getpaint.net',
  'openai.com',
  'reddit.com',
  'spotify.com',
  'thesmackdownhotel.com',
  'wiktionary.org',
  'wwe.com',
  'amd.com',
  'nvidia.com',
  'intel.com',
  'techpowerup.com',
  'guru3d.com',
  'gemini.google.com',
  'jimms.fi',
  'verkkokauppa.com',
  'motonet.fi',
  'datatronic.fi',
  'multitronic.fi',
  'proshop.fi',
  'tori.fi',
  'huuto.net',
  'hintaopas.fi',
  'yliopistonapteekki.fi',
  'findidfb.com',
  'lookup-id.com',
  'facebook.com',
  'yle.fi',
  'hs.fi',
  'mtv.fi',
  'mtvuutiset.fi',
  'kauppalehti.fi',
  'talouselama.fi',
  'suomi.fi',
  'kela.fi',
  'kanta.fi',
  'vero.fi',
  'traficom.fi',
  'poliisi.fi',
  'finlex.fi',
  'posti.fi',
  'matkahuolto.fi',
  'vr.fi',
  'hsl.fi',
  'ilmatieteenlaitos.fi',
  'foreca.fi',
  'op.fi',
  'nordea.fi',
  's-pankki.fi',
  'danskebank.fi',
  'aktia.fi',
  'alandsbanken.fi',
  'poppankki.fi',
  'saastopankki.fi',
  'gigantti.fi',
  'power.fi',
  'hinta.fi',
  'prisma.fi',
  'k-ruoka.fi',
  'tokmanni.fi',
  'puuilo.fi',
  'k-rauta.fi',
  'bauhaus.fi',
  'clasohlson.com',
  'io-tech.fi',
  'muropaketti.com',
  'afterdawn.com',
  'tomshardware.com',
  'notebookcheck.net',
  'videocardz.com',
  'arstechnica.com',
  'bleepingcomputer.com',
  'neowin.net',
  'pcgamer.com',
  'igorslab.de',
  'asus.com',
  'msi.com',
  'corsair.com',
  'coolermaster.com',
  'inno3d.com',
  'galax.com',
  'evga.com',
  'gigabyte.com',
  'aorus.com',
  'asrock.com',
  'zotac.com',
  'palit.com',
  'pny.com',
  'sapphiretech.com',
  'powercolor.com',
  'noctua.at',
  'bequiet.com',
  'fractal-design.com',
  'nzxt.com',
  'lian-li.com',
  'thermaltake.com',
  'seasonic.com',
  'kingston.com',
  'crucial.com',
  'micron.com',
  'samsung.com',
  'westerndigital.com',
  'wd.com',
  'sandisk.com',
  'seagate.com',
  'logitech.com',
  'razer.com',
  'steelseries.com',
  'hyperx.com',
  'acer.com',
  'dell.com',
  'hp.com',
  'lenovo.com',
  'framework.com',
  'microsoft.com',
  'apple.com',
  'mozilla.org',
  'firefox.com',
  'accounts.google.com',
  'support.google.com',
  'developers.google.com',
  'store.google.com',
]);

// URL-prefix exceptions are kept separate so GitHub is not globally exempted.
export const COMPLETE_EXCLUSION_PATH_RULES = Object.freeze([
  Object.freeze({ host: 'github.com', pathPrefix: '/paintdotnet' }),
  Object.freeze({ host: 'github.com', pathPrefix: '/copilot' }),
]);
